# Generated by Django 3.1.1 on 2020-09-30 12:07

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='category/image')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('UNAVAILABLE', 'UNAVAILABLE'), ('COMING_SOON', 'COMING_SOON')], default='AVAILABLE', max_length=20)),
                ('Product_details', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('product_image', models.ImageField(default='', upload_to='product/image')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='', force_format=None, keep_meta=True, quality=100, size=[300, 300], upload_to='product/image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category')),
            ],
        ),
    ]
