# Generated by Django 3.1.1 on 2020-10-01 05:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Product_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
