# Generated by Django 3.1.1 on 2020-10-05 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201001_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
