# Generated by Django 3.1.1 on 2020-10-05 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_products_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
