# Generated by Django 3.1.1 on 2020-10-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_products_product_summery'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='agro'),
        ),
    ]
