# Generated by Django 3.1.1 on 2020-10-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.CharField(default='abc', max_length=255, unique=True),
        ),
    ]
