# Generated by Django 3.1.1 on 2020-10-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pv/image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
