# Generated by Django 3.1.1 on 2020-10-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_gallery_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
