# Generated by Django 3.1.1 on 2020-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
