# Generated by Django 3.1.1 on 2020-10-06 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_gallery_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='video_url',
        ),
    ]
