# Generated by Django 3.1.1 on 2020-10-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_gallery_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
