# Generated by Django 3.1.1 on 2020-10-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_gallery_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(null=True, upload_to='pv/image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='video_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
