# Generated by Django 3.1.1 on 2020-10-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201006_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
