# Generated by Django 3.1.1 on 2020-10-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20201011_1047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
