# Generated by Django 3.1.1 on 2020-10-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
