# Generated by Django 3.1.1 on 2020-09-26 10:05

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('emailaddress', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Department_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default=1, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='', force_format=None, keep_meta=True, quality=100, size=[500, 500], upload_to='team/image')),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job_Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('file', models.FileField(upload_to='file')),
                ('department_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='others.department_name')),
            ],
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_details', models.TextField()),
                ('job_type', models.CharField(choices=[('FULL-TIME', 'FULL-TIME'), ('CONTRACTUAL', 'CONTRACTUAL'), ('PART-TIME', 'PART-TIME'), ('REMOTE', 'REMOTE')], default='FULL-TIME', max_length=11)),
                ('salary', models.CharField(max_length=20)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='others.department_name')),
            ],
        ),
    ]
