# Generated by Django 3.1.1 on 2020-09-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_auto_20200926_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_apply',
            name='job_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='others.circular'),
            preserve_default=False,
        ),
    ]
