# Generated by Django 3.1.1 on 2020-10-01 05:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_auto_20200926_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='job_details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
