# Generated by Django 3.1.1 on 2020-10-01 05:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_auto_20201001_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
