# Generated by Django 3.1.1 on 2020-10-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_auto_20201001_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='circular',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='others.departments'),
        ),
        migrations.DeleteModel(
            name='Department_Name',
        ),
    ]
