# Generated by Django 3.1.1 on 2020-10-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0007_auto_20201004_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
