# Generated by Django 3.1.1 on 2020-10-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0008_auto_20201004_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='facebookId',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='team',
            name='linkedinId',
            field=models.CharField(default='', max_length=225),
        ),
    ]
