# Generated by Django 3.1.1 on 2020-10-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_auto_20201018_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebookId',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedinId',
            field=models.CharField(blank=True, default='', max_length=225),
        ),
    ]
